language: rust
os:
  - linux
  - osx
# Run builds for all the supported trains
rust:
  - nightly
  - beta
  - stable
# This will runs your tests against all three channels, but any breakage in nightly will not fail the rest of build
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

notifications:
  email:
    recipients:
      - wucheng.xidian@qq.com

# The main build
script:
  - cargo build --verbose --all
  - cargo test --verbose --all

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  make install DESTDIR=../../kcov-build &&
  cd ../.. &&
  rm -rf kcov-master &&
  for file in target/debug/leetcode_rust-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"